name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build and push image
        run: |
          docker build -t public.ecr.aws/k2l6q8p1/student-nasser.abdulrahman:${{ github.sha }} .
          docker push public.ecr.aws/k2l6q8p1/student-nasser.abdulrahman:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          password: ${{ secrets.EC2_PASSWORD }}
          envs: GITHUB_SHA
          script: |
            aws ecr-public get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin public.ecr.aws
            docker pull $ECR_REPO:${{ github.sha }}
            docker stop my-site || true
            docker rm my-site || true
            docker run -d --name my-site -p 80:80 $ECR_REPO:${{ github.sha }}
